// PDF Generation Service — jsPDF + jspdf-autotable
// Each function returns a jsPDF instance that can be saved or opened.
// ============================================================================

import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import { formatNumber, getCurrencySymbol } from '@/utils/currency'
import { formatDateLong }                  from '@/utils/date'
import { hoursToHM }                       from '@/utils/time'
import { calculateTimesheetSummary }        from '@/utils/calculations'
import type { Quote, Invoice, Timesheet, UserSettings } from '@/types'

// ── Shared Helpers ─────────────────────────────────────────────────────────

const COLORS = {
  primary:  [17, 24, 39]   as [number, number, number],   // #111827
  accent:   [37, 99, 235]  as [number, number, number],   // #2563EB
  muted:    [107, 114, 128] as [number, number, number],  // #6B7280
  faint:    [209, 213, 219] as [number, number, number],  // #D1D5DB
  white:    [255, 255, 255] as [number, number, number],
}

function money(amount: number, symbol: string): string {
  return `${symbol} ${formatNumber(amount)}`
}

function addPageBorder(doc: jsPDF): void {
  doc.setDrawColor(...COLORS.faint)
  doc.setLineWidth(0.5)
  doc.rect(10, 10, doc.internal.pageSize.width - 20, doc.internal.pageSize.height - 20)
}

function addFooter(doc: jsPDF, text = 'Generated by CrewQuote Pro'): void {
  const y = doc.internal.pageSize.height - 14
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.muted)
  doc.text(text, doc.internal.pageSize.width / 2, y, { align: 'center' })
}

// ── Quote PDF ──────────────────────────────────────────────────────────────

export function generateQuotePDF(quote: Quote, settings: UserSettings): jsPDF {
  const doc    = new jsPDF({ unit: 'mm', format: 'a4' })
  const sym    = getCurrencySymbol(quote.currency)
  const pageW  = doc.internal.pageSize.width
  const margin = 18

  // Header
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, pageW, 38, 'F')

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.white)
  doc.text('QUOTE', margin, 20)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(quote.quoteNumber, margin, 28)

  // Company name (right-aligned)
  const companyName = quote.companyName || settings.companyName || ''
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(companyName, pageW - margin, 18, { align: 'right' })

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.white)
  if (quote.crewName) doc.text(quote.crewName, pageW - margin, 24, { align: 'right' })
  if (quote.role)     doc.text(quote.role,     pageW - margin, 29, { align: 'right' })

  // Metadata block
  let y = 52
  doc.setTextColor(...COLORS.muted)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.text('BILL TO', margin, y)
  doc.text('DATE', pageW - margin - 50, y)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.primary)
  y += 5
  doc.text(quote.client || '—', margin, y)
  doc.text(formatDateLong(quote.date), pageW - margin - 50, y)

  // Line items table
  y += 12
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: (quote.lineItems || []).map(item => [
      item.description,
      String(item.quantity),
      money(item.rate, sym),
      money(item.amount, sym),
    ]),
    theme: 'plain',
    headStyles: {
      fillColor:  COLORS.primary,
      textColor:  COLORS.white,
      fontSize:   8,
      fontStyle:  'bold',
      cellPadding: 4,
    },
    bodyStyles: {
      fontSize:   9,
      cellPadding: 3.5,
      textColor:  COLORS.primary,
    },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 18 },
      2: { halign: 'right', cellWidth: 38 },
      3: { halign: 'right', cellWidth: 38 },
    },
    margin: { left: margin, right: margin },
  })

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 6
  const boxX   = pageW - margin - 72
  let ty       = finalY

  const drawTotal = (label: string, value: string, bold = false) => {
    doc.setFontSize(bold ? 10 : 9)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...(bold ? COLORS.primary : COLORS.muted))
    doc.text(label, boxX, ty)
    doc.text(value, pageW - margin, ty, { align: 'right' })
    ty += 5.5
  }

  drawTotal('Subtotal', money(quote.subtotal, sym))
  if (quote.vat > 0) {
    drawTotal(`VAT (${quote.vat}%)`, money(quote.vatAmount, sym))
  }

  // Total divider line
  doc.setDrawColor(...COLORS.primary)
  doc.setLineWidth(0.6)
  doc.line(boxX, ty, pageW - margin, ty)
  ty += 4
  drawTotal('TOTAL', money(quote.total, sym), true)

  // Notes
  if (quote.notes) {
    ty += 8
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.muted)
    doc.text('NOTES', margin, ty)
    ty += 5
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.primary)
    const lines = doc.splitTextToSize(quote.notes, pageW - margin * 2)
    doc.text(lines, margin, ty)
  }

  addFooter(doc)
  return doc
}

/** Open a quote PDF in a new browser tab */
export function openQuotePDF(quote: Quote, settings: UserSettings): void {
  const doc = generateQuotePDF(quote, settings)
  doc.output('dataurlnewwindow', { filename: `${quote.quoteNumber}.pdf` })
}

// ── Invoice PDF ────────────────────────────────────────────────────────────

export function generateInvoicePDF(invoice: Invoice, settings: UserSettings): jsPDF {
  const doc   = new jsPDF({ unit: 'mm', format: 'a4' })
  const sym   = getCurrencySymbol(invoice.currency)
  const pageW = doc.internal.pageSize.width
  const margin = 18

  // Header
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, pageW, 38, 'F')

  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.white)
  doc.text('INVOICE', margin, 20)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(invoice.invoiceNumber, margin, 28)

  const companyName = invoice.companyName || settings.companyName || ''
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(companyName, pageW - margin, 18, { align: 'right' })

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  if (invoice.crewName) doc.text(invoice.crewName, pageW - margin, 24, { align: 'right' })
  if (invoice.role)     doc.text(invoice.role,     pageW - margin, 29, { align: 'right' })

  // Dates
  let y = 52
  doc.setTextColor(...COLORS.muted)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.text('BILL TO',    margin, y)
  doc.text('ISSUE DATE', pageW - margin - 80, y)
  if (invoice.dueDate) doc.text('DUE DATE', pageW - margin - 30, y)

  y += 5
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.primary)
  doc.text(invoice.clientName || '—', margin, y)
  doc.text(formatDateLong(invoice.issueDate), pageW - margin - 80, y)
  if (invoice.dueDate) doc.text(formatDateLong(invoice.dueDate), pageW - margin - 30, y)

  // Line items
  y += 14
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Rate', 'Amount']],
    body: (invoice.lineItems || []).map(item => [
      item.description,
      String(item.quantity),
      money(item.rate, sym),
      money(item.amount, sym),
    ]),
    theme: 'plain',
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontSize: 8, fontStyle: 'bold', cellPadding: 4 },
    bodyStyles: { fontSize: 9, cellPadding: 3.5, textColor: COLORS.primary },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      0: { cellWidth: 'auto' },
      1: { halign: 'right', cellWidth: 18 },
      2: { halign: 'right', cellWidth: 38 },
      3: { halign: 'right', cellWidth: 38 },
    },
    margin: { left: margin, right: margin },
  })

  // Totals
  const finalY = (doc as any).lastAutoTable.finalY + 6
  const boxX   = pageW - margin - 72
  let ty       = finalY

  const drawTotal = (label: string, value: string, bold = false) => {
    doc.setFontSize(bold ? 10 : 9)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...(bold ? COLORS.primary : COLORS.muted))
    doc.text(label, boxX, ty)
    doc.text(value, pageW - margin, ty, { align: 'right' })
    ty += 5.5
  }

  drawTotal('Subtotal', money(invoice.subtotal, sym))
  if (invoice.vat > 0) drawTotal(`VAT (${invoice.vat}%)`, money(invoice.vatAmount, sym))
  doc.setDrawColor(...COLORS.primary)
  doc.setLineWidth(0.6)
  doc.line(boxX, ty, pageW - margin, ty)
  ty += 4
  drawTotal('TOTAL DUE', money(invoice.total, sym), true)

  // Banking details
  const bd = invoice.bankingDetails || settings.bankingDetails
  const bdEntries = [
    ['Account Name',   bd.accountName],
    ['Bank',           bd.bankName],
    ['Account Number', bd.accountNumber],
    ['Branch Code',    bd.branchCode],
    bd.swiftCode && ['SWIFT', bd.swiftCode],
    bd.iban      && ['IBAN',  bd.iban],
    bd.reference && ['Reference', bd.reference],
  ].filter(Boolean) as string[][]

  if (bdEntries.length > 0) {
    ty += 10
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.muted)
    doc.text('BANKING DETAILS', margin, ty)
    ty += 5

    const colW = (pageW - margin * 2) / 2
    bdEntries.forEach(([k, v], i) => {
      const x = margin + (i % 2 === 1 ? colW : 0)
      if (i % 2 === 0 && i > 0) ty += 8
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...COLORS.muted)
      doc.text(k.toUpperCase(), x, ty)
      doc.setFontSize(9)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...COLORS.primary)
      doc.text(v || '—', x, ty + 4)
    })
  }

  if (invoice.paymentNotes) {
    ty += 14
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...COLORS.muted)
    doc.text('PAYMENT NOTES', margin, ty)
    ty += 5
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.primary)
    const lines = doc.splitTextToSize(invoice.paymentNotes, pageW - margin * 2)
    doc.text(lines, margin, ty)
  }

  addFooter(doc)
  return doc
}

export function openInvoicePDF(invoice: Invoice, settings: UserSettings): void {
  const doc = generateInvoicePDF(invoice, settings)
  doc.output('dataurlnewwindow', { filename: `${invoice.invoiceNumber}.pdf` })
}

// ── Timesheet PDF ──────────────────────────────────────────────────────────

export function generateTimesheetPDF(ts: Timesheet, settings: UserSettings): jsPDF {
  const doc    = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })
  const sym    = getCurrencySymbol(ts.currency)
  const pageW  = doc.internal.pageSize.width
  const margin = 18
  const summary = calculateTimesheetSummary(ts, settings)

  // Header
  doc.setFillColor(...COLORS.primary)
  doc.rect(0, 0, pageW, 34, 'F')

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.white)
  doc.text('TIMESHEET', margin, 16)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(ts.timesheetNumber, margin, 24)

  // Info block (right side of header)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.text(ts.crewName || '', pageW - margin, 13, { align: 'right' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  if (ts.role)           doc.text(ts.role,           pageW - margin, 19, { align: 'right' })
  if (ts.productionName) doc.text(ts.productionName, pageW - margin, 25, { align: 'right' })

  // Weekly table
  const tableY = 42
  autoTable(doc, {
    startY: tableY,
    head: [['Date', 'Location', 'Call', 'Wrap', 'Meal', 'Travel', 'Paid Hrs', 'OT Hrs', 'Day Rate', 'OT Cost', 'Equipment', 'Per Diem', 'Total']],
    body: summary.results.map(e => [
      e.date            || '—',
      e.location        || '—',
      e.callTime        || '—',
      e.wrapTime        || '—',
      `${e.mealBreakMinutes || 0}m`,
      e.trav > 0        ? hoursToHM(e.trav) : '—',
      hoursToHM(e.paid  || 0),
      e.otH > 0         ? hoursToHM(e.otH) : '—',
      money(e.dayRate   || 0, sym),
      e.otC > 0         ? money(e.otC, sym) : '—',
      e.equipmentRental > 0 ? money(e.equipmentRental, sym) : '—',
      e.perDiem > 0     ? money(e.perDiem, sym) : '—',
      money(e.total, sym),
    ]),
    foot: [[
      `${summary.totalDays} days`, '', '', '', '', '',
      hoursToHM(summary.totalPaidH),
      hoursToHM(summary.totalOtH),
      money(summary.totalDayRates, sym),
      money(summary.totalOtCost, sym),
      money(summary.totalEq, sym),
      money(summary.totalPD, sym),
      money(summary.subtotal, sym),
    ]],
    theme: 'plain',
    headStyles: { fillColor: COLORS.primary, textColor: COLORS.white, fontSize: 7, fontStyle: 'bold', cellPadding: 3 },
    bodyStyles: { fontSize: 7.5, cellPadding: 2.5, textColor: COLORS.primary },
    footStyles: { fillColor: [243, 244, 246], textColor: COLORS.primary, fontSize: 7.5, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [249, 250, 251] },
    columnStyles: {
      0: { cellWidth: 22 },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 14, halign: 'center' },
      3: { cellWidth: 14, halign: 'center' },
      4: { cellWidth: 14, halign: 'center' },
      5: { cellWidth: 16, halign: 'center' },
      6: { cellWidth: 16, halign: 'right' },
      7: { cellWidth: 14, halign: 'right' },
      8: { cellWidth: 24, halign: 'right' },
      9: { cellWidth: 22, halign: 'right' },
      10:{ cellWidth: 22, halign: 'right' },
      11:{ cellWidth: 18, halign: 'right' },
      12:{ cellWidth: 26, halign: 'right' },
    },
    margin: { left: margin, right: margin },
  })

  // Totals summary + turnaround warnings
  let finalY = (doc as any).lastAutoTable.finalY + 10
  const halfW = (pageW - margin * 2) / 2

  // Left: warnings
  if (summary.warnings.length > 0) {
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(217, 119, 6) // amber
    doc.text('⚠  TURNAROUND WARNINGS', margin, finalY)
    finalY += 5
    summary.warnings.forEach(w => {
      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.text(`• ${w}`, margin + 2, finalY)
      finalY += 4
    })
  }

  // Right: grand total box
  const boxX = margin + halfW + 20
  let ty = (doc as any).lastAutoTable.finalY + 10

  const drawRow = (label: string, value: string, bold = false) => {
    doc.setFontSize(bold ? 9 : 8)
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setTextColor(...(bold ? COLORS.primary : COLORS.muted))
    doc.text(label, boxX, ty)
    doc.text(value, pageW - margin, ty, { align: 'right' })
    ty += 5
  }

  drawRow('Day Rates',  money(summary.totalDayRates, sym))
  if (summary.totalOtCost > 0) drawRow('Overtime',    money(summary.totalOtCost, sym))
  if (summary.totalEq    > 0) drawRow('Equipment',    money(summary.totalEq,     sym))
  if (summary.totalPD    > 0) drawRow('Per Diem',     money(summary.totalPD,     sym))
  if (summary.totalOther > 0) drawRow('Other',        money(summary.totalOther,  sym))
  if (summary.vatPct     > 0) drawRow(`VAT (${summary.vatPct}%)`, money(summary.vatAmt, sym))
  doc.setDrawColor(...COLORS.primary)
  doc.setLineWidth(0.6)
  doc.line(boxX, ty, pageW - margin, ty)
  ty += 3
  drawRow('TOTAL DUE', money(summary.grandTotal, sym), true)

  // Signature
  ty += 12
  doc.setFontSize(7)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.muted)
  doc.text('CREW SIGNATURE', boxX, ty)
  doc.text('DATE', pageW - margin - 40, ty)
  ty += 10
  doc.setDrawColor(...COLORS.primary)
  doc.line(boxX, ty, boxX + 60, ty)
  doc.line(pageW - margin - 40, ty, pageW - margin, ty)

  addFooter(doc)
  return doc
}

export function openTimesheetPDF(ts: Timesheet, settings: UserSettings): void {
  const doc = generateTimesheetPDF(ts, settings)
  doc.output('dataurlnewwindow', { filename: `${ts.timesheetNumber}.pdf` })
}
