export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          role: string;
          company_name: string;
          email: string;
          phone: string;
          address: string;
          vat_registered: boolean;
          vat_number: string;
          invoice_label: string;
          payment_terms: string;
          invoice_number_history: string[];
          default_currency: Database["public"]["Enums"]["currency_code"];
          default_day_rate: number;
          default_included_hours: number;
          default_equipment_rental: number;
          default_per_diem: number;
          default_vat: number;
          default_overtime_rule: Database["public"]["Enums"]["overtime_rule_id"];
          default_ot_band1_hours: number;
          default_ot_band1_mult: number;
          default_ot_band2_mult: number;
          default_min_turnaround: number;
          default_turnaround_mode: Database["public"]["Enums"]["turnaround_mode"];
          default_turnaround_pen_mult: number;
          meal_breaks_deducted: boolean;
          travel_time_paid: boolean;
          equipment_rental_daily: boolean;
          bank_account_name: string;
          bank_name: string;
          bank_account_number: string;
          bank_branch_code: string;
          bank_swift: string;
          bank_iban: string;
          bank_reference: string;
          business_logo_path: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string;
          role?: string;
          company_name?: string;
          email?: string;
          phone?: string;
          address?: string;
          vat_registered?: boolean;
          vat_number?: string;
          invoice_label?: string;
          payment_terms?: string;
          invoice_number_history?: string[];
          default_currency?: Database["public"]["Enums"]["currency_code"];
          default_day_rate?: number;
          default_included_hours?: number;
          default_equipment_rental?: number;
          default_per_diem?: number;
          default_vat?: number;
          default_overtime_rule?: Database["public"]["Enums"]["overtime_rule_id"];
          default_ot_band1_hours?: number;
          default_ot_band1_mult?: number;
          default_ot_band2_mult?: number;
          default_min_turnaround?: number;
          default_turnaround_mode?: Database["public"]["Enums"]["turnaround_mode"];
          default_turnaround_pen_mult?: number;
          meal_breaks_deducted?: boolean;
          travel_time_paid?: boolean;
          equipment_rental_daily?: boolean;
          bank_account_name?: string;
          bank_name?: string;
          bank_account_number?: string;
          bank_branch_code?: string;
          bank_swift?: string;
          bank_iban?: string;
          bank_reference?: string;
          business_logo_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          user_id: string;
          company_name: string;
          contact_person: string;
          email: string;
          phone: string;
          billing_address: string;
          vat_number: string;
          po_required: boolean;
          vendor_number: string;
          accounts_email: string;
          payment_terms: string;
          default_payment_terms: string;
          preferred_invoice_detail_mode: Database["public"]["Enums"]["invoice_detail_mode"];
          rate_memory: Json | null;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          company_name?: string;
          contact_person?: string;
          email?: string;
          phone?: string;
          billing_address?: string;
          vat_number?: string;
          po_required?: boolean;
          vendor_number?: string;
          accounts_email?: string;
          payment_terms?: string;
          default_payment_terms?: string;
          preferred_invoice_detail_mode?: Database["public"]["Enums"]["invoice_detail_mode"];
          rate_memory?: Json | null;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["clients"]["Insert"]>;
        Relationships: [];
      };
      timesheets: {
        Row: {
          id: string;
          user_id: string;
          timesheet_number: string;
          production_name: string;
          client_id: string | null;
          client_name: string | null;
          client_incomplete: boolean;
          crew_name: string;
          role: string;
          start_date: string | null;
          notes: string | null;
          currency: Database["public"]["Enums"]["currency_code"];
          vat: number;
          status: Database["public"]["Enums"]["timesheet_status"];
          payment_terms: string | null;
          default_day_rate: number | null;
          default_included_hours: number | null;
          default_equipment_rental: number | null;
          default_per_diem: number | null;
          default_overtime_rule: Database["public"]["Enums"]["overtime_rule_id"] | null;
          default_ot_band1_hours: number | null;
          default_ot_band1_mult: number | null;
          default_ot_band2_mult: number | null;
          default_min_turnaround: number | null;
          default_turnaround_mode: Database["public"]["Enums"]["turnaround_mode"] | null;
          default_turnaround_pen_mult: number | null;
          meal_breaks_deducted: boolean | null;
          travel_time_paid: boolean | null;
          equipment_rental_daily: boolean | null;
          invoice_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          timesheet_number: string;
          production_name?: string;
          client_id?: string | null;
          client_name?: string | null;
          client_incomplete?: boolean;
          crew_name?: string;
          role?: string;
          start_date?: string | null;
          notes?: string | null;
          currency?: Database["public"]["Enums"]["currency_code"];
          vat?: number;
          status?: Database["public"]["Enums"]["timesheet_status"];
          payment_terms?: string | null;
          default_day_rate?: number | null;
          default_included_hours?: number | null;
          default_equipment_rental?: number | null;
          default_per_diem?: number | null;
          default_overtime_rule?: Database["public"]["Enums"]["overtime_rule_id"] | null;
          default_ot_band1_hours?: number | null;
          default_ot_band1_mult?: number | null;
          default_ot_band2_mult?: number | null;
          default_min_turnaround?: number | null;
          default_turnaround_mode?: Database["public"]["Enums"]["turnaround_mode"] | null;
          default_turnaround_pen_mult?: number | null;
          meal_breaks_deducted?: boolean | null;
          travel_time_paid?: boolean | null;
          equipment_rental_daily?: boolean | null;
          invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["timesheets"]["Insert"]>;
        Relationships: [];
      };
      timesheet_entries: {
        Row: {
          id: string;
          user_id: string;
          timesheet_id: string;
          entry_order: number;
          date: string;
          production_name: string;
          location: string;
          notes: string;
          call_time: string | null;
          wrap_time: string | null;
          meal_break_minutes: number;
          meal_deducted: boolean;
          travel_start_time: string | null;
          travel_end_time: string | null;
          travel_distance: string;
          travel_paid: boolean;
          day_rate: number;
          included_hours: number;
          overtime_rule: Database["public"]["Enums"]["overtime_rule_id"];
          ot_band1_hours: number;
          ot_band1_mult: number;
          ot_band2_mult: number;
          equipment_rental: number;
          per_diem: number;
          expenses: number;
          expense_description: string;
          rate_snapshot: Json;
          calc_snapshot: Json;
          is_sunday: boolean;
          is_public_holiday: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          timesheet_id: string;
          entry_order?: number;
          date: string;
          production_name?: string;
          location?: string;
          notes?: string;
          call_time?: string | null;
          wrap_time?: string | null;
          meal_break_minutes?: number;
          meal_deducted?: boolean;
          travel_start_time?: string | null;
          travel_end_time?: string | null;
          travel_distance?: string;
          travel_paid?: boolean;
          day_rate?: number;
          included_hours?: number;
          overtime_rule?: Database["public"]["Enums"]["overtime_rule_id"];
          ot_band1_hours?: number;
          ot_band1_mult?: number;
          ot_band2_mult?: number;
          equipment_rental?: number;
          per_diem?: number;
          expenses?: number;
          expense_description?: string;
          rate_snapshot?: Json;
          calc_snapshot?: Json;
          is_sunday?: boolean;
          is_public_holiday?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["timesheet_entries"]["Insert"]>;
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          user_id: string;
          invoice_number: string;
          po_number: string | null;
          issue_date: string;
          due_date: string;
          client_id: string | null;
          client_name: string;
          crew_name: string;
          role: string;
          company_name: string;
          seller_logo_path: string | null;
          seller_snapshot: Json | null;
          production_name: string | null;
          timesheet_number: string;
          timesheet_dates: string | null;
          detail_mode: Database["public"]["Enums"]["invoice_detail_mode"];
          subtotal: number;
          vat: number;
          vat_amount: number;
          total: number;
          paid_amount: number;
          paid_date: string | null;
          balance_due: number;
          currency: Database["public"]["Enums"]["currency_code"];
          status: Database["public"]["Enums"]["invoice_status"];
          banking: Json;
          payment_terms: string | null;
          payment_notes: string;
          notes: string | null;
          from_timesheet_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          invoice_number: string;
          po_number?: string | null;
          issue_date: string;
          due_date: string;
          client_id?: string | null;
          client_name?: string;
          crew_name?: string;
          role?: string;
          company_name?: string;
          seller_logo_path?: string | null;
          seller_snapshot?: Json | null;
          production_name?: string | null;
          timesheet_number?: string;
          timesheet_dates?: string | null;
          detail_mode?: Database["public"]["Enums"]["invoice_detail_mode"];
          subtotal?: number;
          vat?: number;
          vat_amount?: number;
          total?: number;
          paid_amount?: number;
          paid_date?: string | null;
          balance_due?: number;
          currency?: Database["public"]["Enums"]["currency_code"];
          status?: Database["public"]["Enums"]["invoice_status"];
          banking?: Json;
          payment_terms?: string | null;
          payment_notes?: string;
          notes?: string | null;
          from_timesheet_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["invoices"]["Insert"]>;
        Relationships: [];
      };
      invoice_lines: {
        Row: {
          id: string;
          user_id: string;
          invoice_id: string;
          line_order: number;
          description: string;
          quantity: number;
          unit_price: number;
          amount: number;
          is_extra: boolean;
          taxable: boolean;
          category: Database["public"]["Enums"]["invoice_line_category"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          invoice_id: string;
          line_order?: number;
          description?: string;
          quantity?: number;
          unit_price?: number;
          amount?: number;
          is_extra?: boolean;
          taxable?: boolean;
          category?: Database["public"]["Enums"]["invoice_line_category"];
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["invoice_lines"]["Insert"]>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      currency_code: "ZAR" | "USD" | "GBP" | "EUR";
      invoice_detail_mode: "summary" | "detailed" | "summary_timesheet";
      invoice_line_category:
        | "day-rate"
        | "overtime"
        | "equipment"
        | "travel"
        | "expenses"
        | "turnaround"
        | "additional";
      invoice_status: "draft" | "sent" | "paid" | "partial" | "overdue" | "cancelled";
      overtime_rule_id: "sa-film" | "sa-bcea" | "custom";
      timesheet_status: "open" | "submitted" | "invoiced";
      turnaround_mode: "warning" | "penalty" | "manual";
    };
    CompositeTypes: Record<string, never>;
  };
};
